### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by danghung24031992** [maxweb4u/react-native-jwt-io#1]
I using this code : jwt.encode(payload, Config.BWS_SECRET) .But call api then response message Invalid signature , I don't know . Please ,support for me  ,Thank!

**Comment by maxweb4u** [comment]
Hey,

Please provide your source code where you are trying to use this. Then I can help you.

Max.

**Comment by MosesGit** [comment]
Hi, I am getting the same thing. Here is the related code:
```
var base64 = require('base-64');
var utf8 = require('utf8');

var text = '1234';
//var bytes = utf8.encode(text);
//var secret = base64.encode(bytes);
var token = jwt.encode({id: 'Test1', message:'Hello World!'}, text);
console.log(token);
```

So for example, the token is eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlRlc3QxIiwibWVzc2FnZSI6IkhlbGxvIFdvcmxkISJ9.t-OoNH61etl9QV-hAm9Z2uIAX3u0YN-1fgv79o1mqtQ

If I test it at https://jwt.io/, I also get Invalid Signature when I enter my secret key in the field. I have tried with and without base 64 encoding and checking/unchecking the box.

EDIT:
This (https://github.com/kjur/jsrsasign/issues/158) helped me verify the signature successfully. Perhaps it is set to use hexadecimal?

**Comment by Malikkhoja-zz** [comment]
How to decode the token?

**Comment by HenryQz** [comment]
I fixed this issue by update library
"jsrsasign": "^8.0.12"
source reference 
https://github.com/vudvhitech/react-native-jwt-io

**Comment by maxweb4u** [comment]
Close this as it's fixed in last commit
