### ISSUE TITLE
Decode always returns undefined

### ISSUE THREAD

**Issue by Malikkhoja-zz** [maxweb4u/react-native-jwt-io#2]
Hi @maxweb4u ,

The encode works perfectly fine in both the platforms, however, when I try to decode the same using the token and the secret key, it returns undefined.

Any Help would be appreciated.

Thanks in advance

**Comment by HenryQz** [comment]
update library and use function replace
"jsrsasign": "^8.0.12"
```
function parseJwt (token) {
    var base64Url = token.split('.')[1];
    var base64 = decodeURIComponent(atob(base64Url).split('').map(function(c) {
        return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
    }).join(''));

    return JSON.parse(base64);
};
```
source reference 
https://github.com/vudvhitech/react-native-jwt-io

**Comment by maxweb4u** [comment]
Can you create pull request?

**Comment by HenryQz** [comment]
@maxweb4u 
please check https://github.com/maxweb4u/react-native-jwt-io/pull/3

**Comment by maxweb4u** [comment]
PR is merged, issue is closed
